QLTYT-yen2/QLTYT/Controllers/BenhNhanController.cs
using OfficeOpenXml;
using QLTYT.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QLTYT.Controllers
{
  public class BenhNhanController : Controller
  {
    // GET: Benh
    [Authorize]
    public ActionResult Index()
    {
      QLTYTDataContext context = new QLTYTDataContext();
      List<SP_ALLBNResult> bn = context.SP_ALLBN().ToList();
      return View(bn);
    }
    public ActionResult Create()
    {
      QLTYTDataContext context = new QLTYTDataContext();

      List<NhomBenhNhan> listnhombenhnhan = context.NhomBenhNhans.ToList();
      List<GiaDinh> listgiadinh = context.GiaDinhs.ToList();


      ViewBag.nhombenhnhan = listnhombenhnhan;
      ViewBag.giadinh = listgiadinh;

      if (Request.Form.Count > 0)
      {

        String hoten = Request.Form["HoTen"];
        String cccd = Request.Form["CCCD"];
        String bhyt = Request.Form["BHYT"];
        int gioitinh = int.Parse(Request.Form["GioiTinh"]);
        String sdt = Request.Form["SDT"];
        String email = Request.Form["Email"];
        String diachi = Request.Form["DiaChi"];
        float chieucao = float.Parse(Request.Form["ChieuCao"]);
        float cannang = float.Parse(Request.Form["CanNang"]);
        int idnbn = int.Parse(Request.Form["IdNhomBenhNhan"]);
        int idgd = int.Parse(Request.Form["IdGiaDinh"]);


        BenhNhan sp = new BenhNhan();

        sp.HoTen = hoten;
        sp.CCCD = cccd;
        sp.BHYT = bhyt;
        sp.GioiTinh = gioitinh;
        sp.SDT = sdt;
        sp.Email = email;
        sp.ChieuCao = chieucao;
        sp.CanNang = cannang;
        sp.IdNhomBenhNhan = idnbn;
        sp.IdGiaDinh = idgd;



        context.BenhNhans.InsertOnSubmit(sp);
        context.SubmitChanges();
        return RedirectToAction("Index");
      }


      return View();
    }

    public ActionResult Edit(int id)

    {


      QLTYTDataContext context = new QLTYTDataContext();


      BenhNhan sp = context.BenhNhans.FirstOrDefault(x => x.IdBenhNhan == id);

      List<NhomBenhNhan> listnhombenhnhan = context.NhomBenhNhans.ToList();
      List<GiaDinh> listgiadinh = context.GiaDinhs.ToList();

      ViewBag.nhombenhnhan = listnhombenhnhan;
      ViewBag.giadinh = listgiadinh;
      if (sp.NgaySinh != null)
      {
        //ViewBag.NgaySinh = nv.NgaySinh?.ToShortDateString();
        ViewBag.NgaySinh = sp.NgaySinh?.ToString("yyyy-MM-dd");
      }

      if (Request.Form.Count > 0)
      {
        String hoten = Request.Form["HoTen"];
        String cccd = Request.Form["CCCD"];
        String bhyt = Request.Form["BHYT"];
        int gioitinh = int.Parse(Request.Form["GioiTinh"]);
        String sdt = Request.Form["SDT"];
        String email = Request.Form["Email"];
        String diachi = Request.Form["DiaChi"];
        float chieucao = float.Parse(Request.Form["ChieuCao"]);
        float cannang = float.Parse(Request.Form["CanNang"]);
        int idnbn = int.Parse(Request.Form["IdNhomBenhNhan"]);
        int idgd = int.Parse(Request.Form["IdGiaDinh"]);



        sp.HoTen = hoten;
        sp.CCCD = cccd;
        sp.BHYT = bhyt;
        sp.GioiTinh = gioitinh;
        sp.SDT = sdt;
        sp.Email = email;
        sp.ChieuCao = chieucao;
        sp.CanNang = cannang;
        sp.IdNhomBenhNhan = idnbn;
        sp.IdGiaDinh = idgd;





        context.SubmitChanges();
        return RedirectToAction("Index");
      }
      return View(sp);
    }

    public ActionResult Delete(int id)
    {
      QLTYTDataContext context = new QLTYTDataContext();
      BenhNhan sp = context.BenhNhans.FirstOrDefault(x => x.IdBenhNhan == id);
      if (sp != null)
      {

        context.BenhNhans.DeleteOnSubmit(sp);
        context.SubmitChanges();
      }
      return RedirectToAction("Index");
    }


    [HttpPost]
    public ActionResult Upload(HttpPostedFileBase file)
    {
      if (file != null && file.ContentLength > 0)
      {
        string fileName = Path.GetFileName(file.FileName);
        string path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
        file.SaveAs(path);

        using (var package = new ExcelPackage(new FileInfo(path)))
        {
          ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
          var workbook = package.Workbook;
          var worksheet = workbook.Worksheets[0];

          for (int row = 1; row <= worksheet.Dimension.End.Row; row++)
          {
            int idbn = int.Parse(worksheet.Cells[row, 1].Value.ToString());
            int idnbn = int.Parse(worksheet.Cells[row, 2].Value.ToString());
            int idgd = int.Parse(worksheet.Cells[row, 3].Value.ToString());
            string name = worksheet.Cells[row, 4].Value.ToString();
            string cccd = worksheet.Cells[row, 5].Value.ToString();
            string bhyt = worksheet.Cells[row, 6].Value.ToString();
            int gioitinh = int.Parse(worksheet.Cells[row, 7].Value.ToString());
            DateTime ngaysinh = DateTime.Parse(worksheet.Cells[row, 8].Value.ToString());
            string sdt = worksheet.Cells[row, 9].Value.ToString();
            string email = worksheet.Cells[row, 10].Value.ToString();
            string diachi = worksheet.Cells[row, 11].Value.ToString();
            float chieucao = float.Parse(worksheet.Cells[row, 12].Value.ToString());
            float cannang = float.Parse(worksheet.Cells[row, 13].Value.ToString());


            using (var context = new QLTYTDataContext())
            {
              var user = new BenhNhan
              {
                IdBenhNhan = idbn,
                IdNhomBenhNhan = idnbn,
                IdGiaDinh = idgd,
                HoTen = name,
                CCCD = cccd,
                BHYT = bhyt
                  ,
                GioiTinh = gioitinh,
                NgaySinh = ngaysinh,
                SDT = sdt,
                Email = email,
                DiaChi = diachi,
                ChieuCao = chieucao,
                CanNang = cannang
              };
              context.BenhNhans.InsertOnSubmit(user);
              context.SubmitChanges();
            }
          }
        }
      }

      return RedirectToAction("Index");
    }

  }
}

QLTYT-yen2/QLTYT/Controllers/LoaiPhongController.cs
using QLTYT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLTYT.Controllers
{
  public class LoaiPhongController : Controller
  {
    private QLTYTDataContext context = new QLTYTDataContext();
    // GET: LoaiPhong
    public ActionResult LoaiPhong()
    {
      var list = context.LoaiPhongs.ToList();
      return View(list);
    }
    public ActionResult ThemMoiLoaiPhong()
    {
      return View();
    }
    [HttpPost]
    public ActionResult ThemMoiLoaiPhong(LoaiPhong model)
    {
      context.LoaiPhongs.InsertOnSubmit(model);
      context.SubmitChanges();
      return RedirectToAction("LoaiPhong");
    }
    public ActionResult SuaDoiLoaiPhong(int id)
    {
      LoaiPhong lp = context.LoaiPhongs.FirstOrDefault(x => x.IdLoaiPhong == id);
      return View(lp);
    }
    [HttpPost]
    public ActionResult SuaDoiLoaiPhong(LoaiPhong lp)
    {
      LoaiPhong lphong = context.LoaiPhongs.FirstOrDefault(x => x.IdLoaiPhong == lp.IdLoaiPhong);
      lphong.TenLoaiPhong = lp.TenLoaiPhong;
      context.SubmitChanges();
      return RedirectToAction("LoaiPhong");
    }
    [HttpPost]
    public ActionResult XoaLoaiPhong(int id)
    {
      LoaiPhong lphong = context.LoaiPhongs.FirstOrDefault(x => x.IdLoaiPhong == id);
      context.LoaiPhongs.DeleteOnSubmit(lphong);
      context.SubmitChanges();
      return RedirectToAction("LoaiPhong");
    }
  }
}

QLTYT-yen2/QLTYT/Views/LoaiPhong/LoaiPhong.cshtml
@model IEnumerable<QLTYT.Models.LoaiPhong>
@{
    ViewBag.Title = "LoaiPhong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Admin.css" rel="stylesheet">
<link rel="stylesheet" href="~/css/themify-icons/themify-icons.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<div class="table-title">

    @using (Html.BeginForm("Upload", "BenhNhan", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="text" name="file" />
        <input type="submit" value="" />
    }

    <button class="nv btn " type="button" data-toggle="tooltip" data-placement="top"
            title="Thêm ">

        <span?>
            @Html.ActionLink("Thêm", "ThemMoiLoaiPhong")
        </span?>

    </button>
    <div class="seach">
        <form>
            <input type="text" id="Search" placeholder="Search..." class="input"><a href=""><i class="icon ti-search"></i></a>
        </form>
    </div>
    <table class="table-responsive text-nowrap table-bordered" id="myTable">
        <thead>
            <tr class="ex">

                <th>
                    @Html.DisplayName("Mã loại phòng")
                </th>
                <th>
                    @Html.DisplayName("Tên loại phòng")
                </th>
                

                <th></th>
                <th></th>



            </tr>

            @foreach (var item in Model)
            {
                <tr class="Search" id="row_@item.IdLoaiPhong">
                    <td>
                        @Html.DisplayFor(modelItem => item.IdLoaiPhong)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenLoaiPhong)
                    </td>
                    

                    <td>
                        @Html.ActionLink(" ", "SuaDoiLoaiPhong", new { id = item.IdLoaiPhong }, new { @class = "far fa-edit" })
                    </td>

                    @*<td>
                            @Html.ActionLink(" ", "Delete", new { id = item.IdVacXin }, new { @class = "fas fa-trash-alt" })
                        </td>*@
                    <td class="btn-delete js-delete">
                        <a class="delete-link" data-id="@item.IdLoaiPhong" data-name="@item.TenLoaiPhong">
                            <i class="ti-trash"></i>
                        </a>
                    </td>
                </tr>
            }

    </table>








    <style>
        .confirmation-box {
            position: fixed;
            z-index: 9999;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 400px;
            background-color: #fff;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            text-align: center;
        }

            .confirmation-box h3 {
                font-size: 20px;
                margin-bottom: 20px;
            }

            .confirmation-box p {
                font-size: 16px;
                margin-bottom: 20px;
            }

            .confirmation-box .button-group {
                display: flex;
                justify-content: center;
            }

                .confirmation-box .button-group button {
                    margin: 0 10px;
                    padding: 10px 20px;
                    font-size: 16px;
                }

                    .confirmation-box .button-group button.yes {
                        background-color: #e74c3c;
                        color: #fff;
                        border: none;
                    }

                    .confirmation-box .button-group button.no {
                        background-color: #ccc;
                        color: #333;
                        border: none;
                    }
    </style>

    <div id="loader" style="display:none;">
        <img src="~/image/loader.gif" alt="Loading..." />
    </div>

    <script>
        $(document).ready(function () {
            function Contains(text_one, text_two) {
                if (text_one.indexOf(text_two) != -1)
                    return true;
            }
            $("#Search").keyup(function () {
                var searchText = $("#Search").val().toLowerCase();
                $(".Search").each(function () {
                    if (!Contains($(this).text().toLowerCase(), searchText)) {
                        $(this).hide();
                    }
                    else {
                        $(this).show();
                    }
                });
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('.delete-link').click(function (e) {
                e.preventDefault();
                var id = $(this).data('id');
                var name = $(this).data('name');
                var confirmationBoxHtml = '<div class="confirmation-box">' +
                    '<h3>Xóa loại phòng</h3>' +
                    '<p>Bạn có chắc chắn muốn xóa loại phòng <strong>' + name + '</strong>?</p>' +
                    '<div class="button-group">' +
                    '<button class="yes" data-id="' + id + '">Có</button>' +
                    '<button class="no">Không</button>' +
                    '</div>' +
                    '</div>';
                $('body').append(confirmationBoxHtml);
                $('.yes').click(function () {
                    var id = $(this).data('id');
                    deleteVacXin(id);
                    $('.confirmation-box').remove();
                    $('#loader').show();
                });
                $('.no').click(function () {
                    $('.confirmation-box').remove();
                });
            });
        });

        function deleteVacXin(id) {

            // Hiển thị loader
            $('#loader').show();

            // Xóa bệnh
            $.ajax({
                url: '/LoaiPhong/XoaLoaiPhong/' + id,
                type: 'POST',
                success: function (result) {
                    // Ẩn loader
                    $('#loader').hide();
                    // Xóa dòng thông tin bệnh trong bảng
                    $('#row_' + id).remove();
                },
                error: function () {
                    // Ẩn loader
                    $('#loader').hide();
                    alert('Đã xảy ra lỗi khi xóa loại phòng!');
                }
            });

        }
    </script>





</div>

QLTYT-yen2/QLTYT/Views/LoaiPhong/SuaDoiLoaiPhong.cshtml
@model QLTYT.Models.LoaiPhong
@{
    ViewBag.Title = "SuaDoiLoaiPhong";
    Layout = null;
}
<html>
<head>
    <meta charset="utf-8">
    <title>Sửa đổi loại phòng</title>
    <link href="~/css/asset/style1.css" rel="stylesheet" />
</head>
<body>
    <div class="wrapper">
        <div class="title">
            Sửa đổi loại phòng
        </div>
        <form method="post" action="SuaDoiLoaiPhong" enctype="multipart/form-data">
            <div class="field">
                <input type="text" name="IdLoaiPhong" value="@Model.IdLoaiPhong" readonly>

            </div>
            <div class="field">
                <input type="text" name="TenLoaiPhong" value="@Model.TenLoaiPhong">
                <label>Tên loại phòng</label>
            </div>

            <div class="field">
                <input type="submit" value="Cập nhật">
            </div>
            <div class="signup-link">
                <a href="/LoaiPhong/LoaiPhong">Quay lại</a>
            </div>
        </form>
    </div>
</body>
</html>

QLTYT-yen2/QLTYT/Views/LoaiPhong/ThemMoiLoaiPhong.cshtml
@model QLTYT.Models.LoaiPhong
@{
    ViewBag.Title = "ThemMoiLoaiPhong";
    Layout = null;
}
<html>
<head>
    <meta charset="utf-8">
    <title>Thêm loại phòng</title>
    <link href="~/css/asset/style1.css" rel="stylesheet" />
</head>
<body>
    <div class="wrapper">
        <div class="title">
            Thêm loại phòng
        </div>
        <form method="post" action="ThemMoiLoaiPhong">
            <div class="field">
                <input type="text" name="TenLoaiPhong">
                <label>Tên loại phòng</label>
            </div>

            <div class="field">
                <input type="submit" value="Thêm">
            </div>
            <div class="signup-link">
                <a href="/LoaiPhong/LoaiPhong">Quay lại</a>
            </div>
        </form>
    </div>
</body>
</html>