QLTYT/Controllers/TaoPhieuTiemChungController.cs
using QLTYT.Models;
using QLTYT.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLTYT.Controllers
{
  [Authorize]
  public class TaoPhieuTiemChungController : Controller
  {
    // GET: TaoPhieuTiemChung
    private QLTYTDataContext context = new QLTYTDataContext();
    public ActionResult PhieuTiemChung()
    {
      var list = new MutipleData2();
      list.phieuTiemChungs = context.PhieuTiemChungs
                                .Join(context.NhanViens, ptc => ptc.IdNhanVien, nv => nv.IdNhanVien, (ptc, nv) => new { PhieuTiemChung = ptc, NhanVien = nv })
                                .Join(context.Phongs, ptcl => ptcl.PhieuTiemChung.IdPhong, phong => phong.IdPhong, (ptcl, phong) => new { ptcl.PhieuTiemChung, ptcl.NhanVien, Phong = phong })
                                .Join(context.BenhNhans, ptclp => ptclp.PhieuTiemChung.IdBenhNhan, bn => bn.IdBenhNhan, (ptclp, bn) => new { ptclp.PhieuTiemChung, ptclp.NhanVien, ptclp.Phong, BenhNhan = bn })
                                .Select(x => x.PhieuTiemChung);
      list.nhanViens = context.NhanViens
                      .Join(context.NhomNhanViens, nv => nv.IdNhomNhanVien, nnv => nnv.IdNhomNhanVien, (nv, nnv) => new { NhanVien = nv, NhomNhanVien = nnv })
                      .Select(x => x.NhanVien);
      list.phongs = from phong in context.Phongs
                    join loaiPhong in context.LoaiPhongs on phong.IdLoaiPhong equals loaiPhong.IdLoaiPhong
                    select phong;
      list.benhNhans = context.BenhNhans
                .Join(context.NhomBenhNhans, bn => bn.IdNhomBenhNhan, nb => nb.IdNhomBenhNhan, (bn, nb) => new { BenhNhan = bn, NhomBenhNhan = nb })
                .Select(x => x.BenhNhan);
      return View(list);
    }
    public ActionResult TaoPhieuTiemChung()
    {
      var list = new MutipleData2();
      list.phieuTiemChungs = context.PhieuTiemChungs
                                .Join(context.NhanViens, ptc => ptc.IdNhanVien, nv => nv.IdNhanVien, (ptc, nv) => new { PhieuTiemChung = ptc, NhanVien = nv })
                                .Join(context.Phongs, ptcl => ptcl.PhieuTiemChung.IdPhong, phong => phong.IdPhong, (ptcl, phong) => new { ptcl.PhieuTiemChung, ptcl.NhanVien, Phong = phong })
                                .Join(context.BenhNhans, ptclp => ptclp.PhieuTiemChung.IdBenhNhan, bn => bn.IdBenhNhan, (ptclp, bn) => new { ptclp.PhieuTiemChung, ptclp.NhanVien, ptclp.Phong, BenhNhan = bn })
                                .Select(x => x.PhieuTiemChung);
      list.nhanViens = context.NhanViens
                      .Join(context.NhomNhanViens, nv => nv.IdNhomNhanVien, nnv => nnv.IdNhomNhanVien, (nv, nnv) => new { NhanVien = nv, NhomNhanVien = nnv })
                      .Select(x => x.NhanVien);
      list.phongs = context.Phongs
                  .Where(p => p.LoaiPhong.TenLoaiPhong == "Phòng tiêm chủng" && p.TinhTrang != "Tạm ngưng")
                  .ToList();
      list.benhNhans = context.BenhNhans
                .Join(context.NhomBenhNhans, bn => bn.IdNhomBenhNhan, nb => nb.IdNhomBenhNhan, (bn, nb) => new { BenhNhan = bn, NhomBenhNhan = nb })
                .Select(x => x.BenhNhan);
      return View(list);
    }

    [HttpPost]
    public ActionResult TaoPhieuTiemChung(PhieuTiemChung ptc)
    {
      ptc.NgayTao = DateTime.Now;
      context.PhieuTiemChungs.InsertOnSubmit(ptc);
      context.SubmitChanges();
      return RedirectToAction("PhieuTiemChung");
    }

    [HttpGet]
    public ActionResult SuaDoiPhieuTiemChung(int id)
    {
      var list = new MutipleData2();
      list.phieuTiemChungs = context.PhieuTiemChungs.Where(p => p.IdSoPhieu == id).ToList();
      list.nhanViens = context.NhanViens.ToList();
      list.phongs = context.Phongs
                  .Where(p => p.LoaiPhong.TenLoaiPhong == "Phòng tiêm chủng" && p.TinhTrang != "Tạm ngưng")
                  .ToList();
      list.benhNhans = context.BenhNhans.Where(p => p.NhomBenhNhan.TenNhom == "Trẻ em").ToList();
      return View(list);
    }
    [HttpPost]
    public ActionResult SuaDoiPhieuTiemChung(PhieuTiemChung ptc)
    {
      PhieuTiemChung phieu = context.PhieuTiemChungs.FirstOrDefault(x => x.IdSoPhieu == ptc.IdSoPhieu);
      phieu.IdNhanVien = ptc.IdNhanVien;
      phieu.IdPhong = ptc.IdPhong;
      phieu.IdBenhNhan = ptc.IdBenhNhan;
      context.SubmitChanges();
      return RedirectToAction("PhieuTiemChung");
    }
    [HttpPost]
    public ActionResult XoaPhieuTiemChung(int id)
    {
      PhieuTiemChung ptc = context.PhieuTiemChungs.FirstOrDefault(x => x.IdSoPhieu == id);
      context.PhieuTiemChungs.DeleteOnSubmit(ptc);
      context.SubmitChanges();
      return RedirectToAction("PhieuTiemChung");
    }
    [HttpGet]
    public ActionResult ChiTietPhieuTiemChung(int id)
    {
      var list = new MutipleData2();
      ViewBag.CTPTC = id;

      list.phieuTiemChungs = (
          from pt in context.PhieuTiemChungs
          join nv in context.NhanViens on pt.IdNhanVien equals nv.IdNhanVien
          join ph in context.Phongs on pt.IdPhong equals ph.IdPhong
          join bn in context.BenhNhans on pt.IdBenhNhan equals bn.IdBenhNhan
          where pt.IdSoPhieu == id
          select pt
      ).ToList();

      list.nhanViens = context.NhanViens.ToList();


      list.phongs = (
          from ph in context.Phongs
          join lp in context.LoaiPhongs on ph.IdPhong equals lp.IdLoaiPhong
          where lp.TenLoaiPhong == "Phòng tiêm chủng" && ph.TinhTrang != "Tạm ngưng"
          select ph
      ).ToList();

      list.benhNhans = context.BenhNhans.Where(p => p.NhomBenhNhan.TenNhom == "Trẻ em").ToList();


      list.chiTietTiemChungs = (
          from cttc in context.ChiTietTiemChungs
          join pu in context.PhanUngs on cttc.IdPhanUng equals pu.IdPhanUng
          join vx in context.VacXins on cttc.IdVacXin equals vx.IdVacXin
          where cttc.IdSoPhieu == id
          select cttc
      ).ToList();


      list.chiTietTrieuChungs = (
          from cttc in context.ChiTietTrieuChungs
          join tc in context.TrieuChungs on cttc.IdTrieuChung equals tc.IdTrieuChung
          join pu in context.PhanUngs on cttc.IdPhanUng equals pu.IdPhanUng
          select cttc
      ).ToList();

      return View(list);
    }

    public ActionResult TaoChiTietPhieuTiemChung(int id)
    {
      var list = new MutipleData2();
      ViewBag.CTPTC = id;
      // Lấy danh sách chi tiết tiêm chủng kèm theo thông tin liên quan
      var chiTietTiemChungs = (from cttc in context.ChiTietTiemChungs
                               join ptc in context.PhieuTiemChungs on cttc.IdSoPhieu equals ptc.IdSoPhieu
                               join pu in context.PhanUngs on cttc.IdPhanUng equals pu.IdPhanUng
                               join vx in context.VacXins on cttc.IdVacXin equals vx.IdVacXin
                               select new
                               {
                                 ChiTietTiemChung = cttc,
                                 PhieuTiemChung = ptc,
                                 PhanUng = pu,
                                 VacXin = vx
                               }).ToList();

      // Chuyển danh sách kết quả sang đối tượng MutipleData2
      list.chiTietTiemChungs = chiTietTiemChungs.Select(x => x.ChiTietTiemChung).ToList();
      list.phieuTiemChungs = chiTietTiemChungs.Select(x => x.PhieuTiemChung).Distinct().ToList();
      list.phanUngs = chiTietTiemChungs.Select(x => x.PhanUng).Distinct().ToList();
      list.vacXins = chiTietTiemChungs.Select(x => x.VacXin).Distinct().ToList();

      return View(list);
    }

    [HttpPost]
    public ActionResult TaoChiTietPhieuTiemChung(ChiTietTiemChung cttc, HttpPostedFileBase HinhAnhUpload)
    {
      context.ChiTietTiemChungs.InsertOnSubmit(cttc);
      context.SubmitChanges();
      if (HinhAnhUpload != null && HinhAnhUpload.ContentLength > 0)
      {
        int id = int.Parse(context.ChiTietTiemChungs.ToList().Last().IdChiTietTiemChung.ToString());
        string _FileName = "";
        int index = HinhAnhUpload.FileName.IndexOf('.');
        _FileName = "kh" + id.ToString() + "." + HinhAnhUpload.FileName.Substring(index + 1);
        string _path = Path.Combine(Server.MapPath("~/image"), _FileName);
        HinhAnhUpload.SaveAs(_path);

        ChiTietTiemChung cttc1 = context.ChiTietTiemChungs.FirstOrDefault(x => x.IdChiTietTiemChung == id);
        cttc1.HinhAnh = _FileName;
        context.SubmitChanges();
      }

      return RedirectToAction("PhieuTiemChung");
    }
    public ActionResult SuaDoiChiTietPhieuTiemChung(int id)
    {
      var list = new MutipleData2();
      list.chiTietTiemChungs = context.ChiTietTiemChungs.Where(p => p.IdChiTietTiemChung == id).ToList();
      list.phanUngs = context.PhanUngs.ToList();
      list.vacXins = context.VacXins.ToList();
      return View(list);
    }
    [HttpPost]
    public ActionResult SuaDoiChiTietPhieuTiemChung(ChiTietTiemChung cttc, HttpPostedFileBase HinhAnhUpload)
    {
      ChiTietTiemChung chitiet = context.ChiTietTiemChungs.FirstOrDefault(x => x.IdChiTietTiemChung == cttc.IdChiTietTiemChung);
      string path = uploadimage(HinhAnhUpload);


      cttc.HinhAnh = path;

      if (ModelState.IsValid)
      {
        cttc.IdChiTietTiemChung = cttc.IdChiTietTiemChung;
        cttc.IdSoPhieu = cttc.IdSoPhieu;
        cttc.IdPhanUng = chitiet.IdPhanUng;
        cttc.IdVacXin = chitiet.IdVacXin;
        cttc.DiaDiem = chitiet.DiaDiem;
        cttc.GhiChu = chitiet.GhiChu;
        context.SubmitChanges();
        return RedirectToAction("PhieuTiemChung");
      }
      return View(cttc);
    }
    public string uploadimage(HttpPostedFileBase file)
    {
      Random r = new Random();
      string path = "-1";
      int random = r.Next();
      if (file != null && file.ContentLength > 0)
      {
        string extension = Path.GetExtension(file.FileName);

QLTYT/Views/TaoPhieuTiemChung/PhieuTiemChung.cshtml
@model QLTYT.ViewModel.MutipleData2
@{ ViewBag.Title = "PhieuTiemChung";
        Layout = "~/Views/Shared/_Layout.cshtml"; }

<link href="~/Content/Admin.css" rel="stylesheet">
<link rel="stylesheet" href="~/css/themify-icons/themify-icons.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<div class="table-title">

  <h2>Quản lý thông tin phiếu tiêm chủng</h2>
  <br />
  <br />
  <br />

  <button class="nv btn " type="button" data-toggle="tooltip" data-placement="top"
          title="Thêm ">

    <span?>
      @Html.ActionLink("Thêm", "TaoPhieuTiemChung")
    </span?>

  </button>
  <div class="seach">
    <form>
      <input type="text" id="Search" placeholder="Tìm kiếm..." class="input"><a href=""><i class="icon ti-search"></i></a>
    </form>
  </div>
  <table class="table-responsive text-nowrap table-bordered" id="myTable">
    <thead>
      <tr class="ex">

        <th>
          @Html.DisplayName("Số phiếu")
        </th>
        <th>
          @Html.DisplayName("Tên nhân viên")
        </th>
        <th>
          @Html.DisplayName("Tên phòng")
        </th>
        <th>
          @Html.DisplayName("Loại phòng")
        </th>
        <th>
          @Html.DisplayName("Tên bệnh nhân")
        </th>
        <th>
          @Html.DisplayName("Nhóm bệnh nhân")
        </th>
        <th>
          @Html.DisplayName("Ngày tạo")
        </th>

        <th></th>
        <th></th>
        <th></th>



      </tr>

      @foreach (var item in Model.phieuTiemChungs)
      {
<tr class="Search" id="row_@item.IdSoPhieu">
  <td>
    @Html.DisplayFor(modelItem => item.IdSoPhieu)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.NhanVien.HoTen)
  </td>

  <td>
    @Html.DisplayFor(modelItem => item.Phong.TenPhong)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.Phong.LoaiPhong.TenLoaiPhong)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.BenhNhan.HoTen)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.BenhNhan.NhomBenhNhan.TenNhom)
  </td>
  <td>
    @Html.DisplayFor(modelItem => item.NgayTao)
  </td>

  <td>
    @Html.ActionLink(" ", "ChiTietPhieuTiemChung", new { id = item.IdSoPhieu }, new { @class = "far fa-eye" })
  </td>
  <td>
    @Html.ActionLink(" ", "SuaDoiPhieuTiemChung", new { id = item.IdSoPhieu }, new { @class = "far fa-edit" })
  </td>

  @*<td>
        @Html.ActionLink(" ", "Delete", new { id = item.IdVacXin }, new { @class = "fas fa-trash-alt" })
    </td>*@
  <td class="btn-delete js-delete">
    <a class="delete-link" data-id="@item.IdSoPhieu" data-name="@item.BenhNhan.HoTen">
      <i class="fas fa-trash-alt"></i>
    </a>
  </td>
</tr>
}

  </table>








  <style>
    .confirmation-box {
      position: fixed;
      z-index: 9999;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      width: 400px;
      background-color: #fff;
      padding: 20px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
      text-align: center;
    }

      .confirmation-box h3 {
        font-size: 20px;
        margin-bottom: 20px;
      }

      .confirmation-box p {
        font-size: 16px;
        margin-bottom: 20px;
      }

      .confirmation-box .button-group {
        display: flex;
        justify-content: center;
      }

        .confirmation-box .button-group button {
          margin: 0 10px;
          padding: 10px 20px;
          font-size: 16px;
        }

          .confirmation-box .button-group button.yes {
            background-color: #e74c3c;
            color: #fff;
            border: none;
          }

          .confirmation-box .button-group button.no {
            background-color: #ccc;
            color: #333;
            border: none;
          }
  </style>

  <div id="loader" style="display:none;">
    <img src="~/image/loader.gif" alt="Loading..." />
  </div>

  <script>
    $(document).ready(function () {
      function Contains(text_one, text_two) {
        if (text_one.indexOf(text_two) != -1)
          return true;
      }
      $("#Search").keyup(function () {
        var searchText = $("#Search").val().toLowerCase();
        $(".Search").each(function () {
          if (!Contains($(this).text().toLowerCase(), searchText)) {
            $(this).hide();
          }
          else {
            $(this).show();
          }
        });
      });
    });
  </script>

  <script>
    $(document).ready(function () {
      $('.delete-link').click(function (e) {
        e.preventDefault();
        var id = $(this).data('id');
        var name = $(this).data('name');
        var confirmationBoxHtml = '<div class="confirmation-box">' +
          '<h3>Xóa phiếu tiêm chủng</h3>' +
          '<p>Bạn có chắc chắn muốn xóa phiếu tiêm chủng của <strong>' + name + '</strong>?</p>' +
          '<div class="button-group">' +
          '<button class="yes" data-id="' + id + '">Có</button>' +
          '<button class="no">Không</button>' +
          '</div>' +
          '</div>';
        $('body').append(confirmationBoxHtml);
        $('.yes').click(function () {
          var id = $(this).data('id');
          deleteVacXin(id);
          $('.confirmation-box').remove();
          $('#loader').show();
        });
        $('.no').click(function () {
          $('.confirmation-box').remove();
        });
      });
    });

    function deleteVacXin(id) {

      // Hiển thị loader
      $('#loader').show();

      // Xóa bệnh
      $.ajax({
        url: '/TaoPhieuTiemChung/XoaPhieuTiemChung/' + id,
        type: 'POST',
        success: function (result) {
          // Ẩn loader
          $('#loader').hide();
          // Xóa dòng thông tin bệnh trong bảng
          $('#row_' + id).remove();
        },
        error: function () {
          // Ẩn loader
          $('#loader').hide();
          alert('Đã xảy ra lỗi khi xóa phiếu tiêm chủng!');
        }
      });

    }
  </script>





</div>

QLTYT/Views/TaoPhieuTiemChung/SuaDoiChiTietPhieuTiemChung.cshtml
@model QLTYT.ViewModel.MutipleData2
@{
    ViewBag.Title = "SuaDoiChiTietPhieuTiemChung";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Admin.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<div class="table-title">

    <h2>Sửa Đổi Chi Tiết Phiếu Tiêm Chủng</h2>
    <br />
    <br />
    <br />
    <form method="post" action="SuaDoiChiTietPhieuTiemChung" enctype="multipart/form-data">
        @foreach (var item in Model.chiTietTiemChungs)
        {
            <div class="select">
                <label>Mã chi tiết</label>
                <input type="text" name="IdchiTietTiemChung" value="@item.IdChiTietTiemChung" readonly/>
            </div>
            <div class="select">
                <label>Mã số phiếu</label>
                <input type="text" name="IdSoPhieu" value="@item.IdSoPhieu" readonly/>
            </div>
            <br />
            <div class="select">
                <label>Mã phản ứng</label>
                <select name="IdPhanUng" id="IdPhanUng" class="form-select">
                    <option selected disabled>Chọn tên phản ứng - mức độ</option>
                    @foreach (var item1 in Model.phanUngs)
                    {
                        <option value="@item.IdPhanUng" @(item1.IdPhanUng == item.IdPhanUng ? "selected" : "")>@item1.TenPhanUng - @item1.MucDo</option>
                    }
                </select>
            </div>
            <br />
            <div class="select">
                <label>Tên vắc xin</label>
                <select name="IdVacXin" id="IdVacXin" class="form-select">
                    <option selected disabled>Chọn vắc xin</option>
                    @foreach (var item1 in Model.vacXins)
                    {

                        <option value="@item1.IdVacXin" @(item1.IdVacXin == item.IdVacXin ? "selected" : "")>@item1.TenVacXin</option>
                    }
                </select>
            </div>
            <br />
            <div class="select">
                <label>Địa điểm</label>
                <input type="text" name="DiaDiem" value="@item.DiaDiem" />
            </div>
            <br />
            <div class="select">
                <label>Ghi chú</label>
                <input type="text" name="GhiChu" value="@item.GhiChu" />
            </div>
            <br />
            <div class="select">
                <label>Hình ảnh</label>
                <img src="~/image/@item.HinhAnh" alt="Hình ảnh" width="200" height="200" />
                <input type="file" name="HinhAnhUpload" accept="image/*" />
            </div>
            <br />
            <div class="form-group" style="justify-content:space-between">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-secondary">
                        @Html.ActionLink("Quay lại", "PhieuTiemChung")
                    </button>
                    <button class="btn btn-primary" type="submit" data-toggle="tooltip" data-placement="top"
                            title="Cập nhật">
                        Cập nhật
                    </button>
                </div>

            </div>
        }
    </form>
    @*<script>
        $(document).ready(function () {
            $('#themPhieu').click(function () {
                var idSoPhieu = $(this).closest('tr').find('td:eq(0)').text();
                $('input[name="IdSoPhieu"]').val(idSoPhieu);
            });
        });
        </script>*@

</div>

QLTYT/Views/TaoPhieuTiemChung/TaoChiTietPhieuTiemChung.cshtml
@model QLTYT.ViewModel.MutipleData2
@{
    ViewBag.Title = "TaoChiTietPhieuTiemChung";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Admin.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<div class="table-title">

    <h2>Tạo Chi Tiết Phiếu Tiêm Chủng</h2>
    <br />
    <br />
    <br />
    <form method="post" action="TaoChiTietPhieuTiemChung" enctype="multipart/form-data">
        <div class="select">
            @*<label>Mã số phiếu</label>*@
            <input type="text" name="IdSoPhieu" value="@ViewBag.CTPTC"  hidden/>
        </div>
        <br />
        <div class="select">
            <label>Mã phản ứng</label>
            <select name="IdPhanUng" id="IdPhanUng" class="form-select">
                <option selected disabled>Chọn tên phản ứng - mức độ</option>
                @foreach (var item in Model.phanUngs)
                {
                    <option value="@item.IdPhanUng">@item.TenPhanUng - @item.MucDo</option>
                }
            </select>
        </div>
        <br />
        <div class="select">
            <label>Tên vắc xin</label>
            <select name="IdVacXin" id="IdVacXin" class="form-select">
                <option selected disabled>Chọn vắc xin</option>
                @foreach (var item in Model.vacXins)
                {

                    <option value="@item.IdVacXin">@item.TenVacXin</option>
                }
            </select>
        </div>
        <br />
        <div class="select">
            <label>Địa điểm</label>
            <input type="text" name="DiaDiem" />
        </div>
        <br />
        <div class="select">
            <label>Ghi chú</label>
            <input type="text" name="GhiChu" />
        </div>
        <br />
        <div class="select">
            <label>Hình ảnh</label>
            <input type="file" name="HinhAnhUpload" accept="image/*" />
        </div>
        <br />
        <div class="form-group" style="justify-content:space-between">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-secondary">
                    @Html.ActionLink("Quay lại", "PhieuTiemChung")
                </button>
                <button class="btn btn-primary" type="submit" data-toggle="tooltip" data-placement="top"
                        title="Tạo mới ">
                    Tạo mới
                </button>
            </div>

        </div>
    </form>
    @*<script>
    $(document).ready(function () {
        $('#themPhieu').click(function () {
            var idSoPhieu = $(this).closest('tr').find('td:eq(0)').text();
            $('input[name="IdSoPhieu"]').val(idSoPhieu);
        });
    });
    </script>*@

</div>